### ISSUE TITLE
Command to list known hosts

### ISSUE THREAD

**Issue by kenrachynski** [MatteoSp/hubot-schtasks#1]
I'm setting up a bot for use by others in my company. They may or may not know which hosts have been configured in the bot. It would be really useful to have a _st list_ command to show which hosts are currently configured.

**Comment by MatteoSp** [comment]
Solved by commit 34a9abc02f7d573ddd804a477da94a31fbc99646 (https://github.com/MatteoSp/hubot-schtasks/commit/34a9abc02f7d573ddd804a477da94a31fbc99646)
