### ISSUE TITLE
Case insensitive hosts

### ISSUE THREAD

**Issue by kenrachynski** [MatteoSp/hubot-schtasks#2]
Having configured my bot, I forgot how I specifically labeled my hosts. Currently _st on HOST_ is case sensitive and will just send me a blank message if I mistype it. Could we have the host name test compare regardless of case?

**Comment by MatteoSp** [comment]
Solved, see commit 9c54be542f536633e5c3a1444ba333666e071839 (https://github.com/MatteoSp/hubot-schtasks/commit/9c54be542f536633e5c3a1444ba333666e071839).
